### ISSUE TITLE
Bulk Edit does not work with Nautobot 2.3.14

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot-app-data-validation-engine#191]
### Environment
* Python version: 3.11
* Nautobot version:  2.3.14
* nautobot-data-validation-engine version:  3.2.0

### Expected Behavior

Ability to Bulk Edit one of the Data Validation Rulesets.

### Observed Behavior

AttributeError at /plugins/nautobot-data-validation-engine/min-max-rules/edit/
'MinMaxValidationRuleBulkEditForm' object has no attribute 'model'

### Steps to Reproduce
1. Create a Min/Max Rule
2. View the new rule in the Min/Max Rules list view
3. Select the rule and try to "Edit Selected"

**Comment by smk4664** [comment]
This was caught by the Upstream Testing, and I have a fix I will be putting in a PR soon.
