### PR TITLE
Resolve issue with Bulk Edit form

### LINKED ISSUE #191: Bulk Edit does not work with Nautobot 2.3.14
### Environment
* Python version: 3.11
* Nautobot version:  2.3.14
* nautobot-data-validation-engine version:  3.2.0

### Expected Behavior

Ability to Bulk Edit one of the Data Validation Rulesets.

### Observed Behavior

AttributeError at /plugins/nautobot-data-validation-engine/min-max-rules/edit/
'MinMaxValidationRuleBulkEditForm' object has no attribute 'model'

### Steps to Reproduce
1. Create a Min/Max Rule
2. View the new rule in the Min/Max Rules list view
3. Select the rule and try to "Edit Selected"

### PR DESCRIPTION
**Pull request by smk4664**
Closes: #191 

This PR corrects the form class inheritance.

### CODE REVIEW

**Comment by glennmatthews** [comment]
Seems reasonable to me, but is there any change we can/should make in core to either allow for the variant MRO or more proactively raise a warning if it's incorrect?

**Review by DistantVoyager — APPROVED** [review]

**Comment by smk4664** [comment]
> Seems reasonable to me, but is there any change we can/should make in core to either allow for the variant MRO or more proactively raise a warning if it's incorrect?

Thanks! I submitted an issue to nautobot/nautobot, but I believe a the issue is with TagsBulkEditFormMixin inheriting from forms.Form instead of BulkEditForm.
